version: '3.8'

services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    entrypoint: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]  # Ожидание перед запуском
    restart: unless-stopped  # Гарантирует перезапуск при сбоях

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shareit
    entrypoint: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]  # Ожидание перед запуском
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shareit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Гарантирует, что БД не выключится

volumes:
  postgres_data: